version: '3'
services:
  #App
  challenge-app:
      build:
        context: ./challengeApp
        dockerfile: Dockerfile
      container_name: challengeApp
      restart: unless-stopped
      working_dir: /app
      ports:
      - "80:8080"
      volumes:
      - ./challengeApp/:/app