version: '3'
services:
  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8001:80"
    volumes:
      - ./app1/:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #App
  challengeApp:
      build: ./challengeApp
      container_name: challengeApp
      restart: unless-stopped
      tty: true
      ports:
      - "9001:9000"
      volumes:
      - ./app1/:/var/www
      networks:
      - app-network

#Docker Network
networks:
    app-network:
      driver: bridge